environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

build: false

install:
  - git submodule update --init --recursive
  - ps: |
      Invoke-WebRequest `
        -Uri https://github.com/rcook/rust-appveyor-build-pack/releases/latest/download/rust-appveyor-build-pack.ps1 `
        -OutFile rust-appveyor-build-pack.ps1
  - ps: .\rust-appveyor-build-pack.ps1
  - ps: .\rust-appveyor-build-pack\install.ps1

build_script:
  - ps: .\rust-appveyor-build-pack\build.ps1

test_script:
  - ps: .\rust-appveyor-build-pack\test.ps1

artifacts:
  - name: zip
    path: target/dist/*.zip
  - path: target/dist/build.txt
  - path: target/dist/version.txt
  - path: target/debug/debug-test.log
  - path: target/release/release-test.log

deploy:
  description: Official release from AppVeyor
  artifact: zip
  auth_token:
    secure: KnsNe82iVYE0/gNPx55EdNiJ3q5rM9GKu+y8E/Fz5tCnybP3NZj0PEbLabX9wZzY
  provider: GitHub
  on:
    branch: /v.+/
    APPVEYOR_REPO_TAG: true
